### PR TITLE
Modern interface

### PR DESCRIPTION
**Pull request by minad**
Concerning issue #3
- Add Semigroup and Monoid instances
- Add <#> and <##> operators

### CODE REVIEW

**Comment by minad** [comment]
@david-christiansen It seems that development has switched to https://github.com/ekmett/wl-pprint-extras?

**Comment by david-christiansen** [comment]
Sorry to be a bit slow responding.

At some point, I'd like to port Idris over to `wl-pprint-extras`, but I don't know when that will be. So this library should definitely continue to receive maintenance.

These changes are definitely an improvement. I'm a bit in doubt about the `Modern` namespace, however, because names like that don't age very well. What happens the next time we need it updated? I'm at a bit of a loss as to what else to call it though. Let me mull at it for a day or two, before I merge, unless you have an alternative namespace idea. If I can't think of something less prone to bit-rot, I'll merge as-is.

And thank you very much!

**Comment by david-christiansen** [comment]
Oh, and `<#>` and `<##>` should probably have Haddock.

**Comment by minad** [comment]
Hi,

the name Modern was more a suggestion, feel free to rename it! I asked @ekmett on irc and he said that https://github.com/ekmett/wl-pprint-extras is going to be developed further and a new release will be made at some undefined point in the future ;)
Since the wl-pprint-extras library is already more general and mostly compatible (Foldable instead of lists, point effects, monadic structure), I would suggest the efforts should be focused there. Maybe you could keep this library as is or merge this backward compatible PR and as soon as we have the new wl-pprint-extras, you could mark this one as deprecated. What do you think?

Daniel

**Comment by minad** [comment]
Then the question is if one could also add the operators <#> and <##> to wl-pprint-extras or we shouldn't add them here...

**Comment by ekmett** [comment]
@minad: The changes to `wl-pprint-extras` and `ansi-wl-pprint` we have in mind actually came from a discussion with @david-christiansen in the first place. ;)

That said, he's demonstrated an ability to ship a package, and I've only demonstrated an ability to talk about shipping one. =)

**Comment by minad** [comment]
@david-christiansen @ekmett A while ago, I forked annotated-wl-pprint/wl-pprint-extras and modified it slightly for my use case (no free monad, but annotations and modernized api). See here https://github.com/minad/wl-pprint-annotated and also https://github.com/minad/wl-pprint-console for colored output. It should act as a drop in replacement for annotated-wl-pprint and maybe we can merge the things together again.

**Pull request closed without merging**
